### ISSUE TITLE
Have multiple branches: Chromium, FF and Userscript

### ISSUE THREAD

**Issue by ghost** [chrismbryant/amazon-confidence-interval#2]

**Comment by musicin3d** [comment]
Core logic for scraping and calculation can probably be stored in `/src/shared` and included in each `/src/<browser>` as needed. It's been a while since I fiddled with chrome extensions, but that should work. I'm pretty sure it'll be trivial if we build the distribution with webpack or gulp.

**Comment by ghost** [comment]
Why use folders instead of branches?

**Comment by chrismbryant** [comment]
Having dev branches for each browser makes sense, but I think there should also still be folders so that all the code is there in the master branch

**Comment by musicin3d** [comment]
I'm not sure if this point is for or against using folders... With folders, merging changes to shared code would require all platforms to be updated as well. Whereas, using separate branches would allow each platform to update independently. 

Perhaps going the "branches" route would mean fewer surprises?

**Comment by musicin3d** [comment]
In the spirit of not fixing it until it breaks, I'm returning to my original position. Folders are simpler to use and understand (and we've already started). **If** we end up with several platforms and **if** we actually run into trouble then it will not be too much trouble to move to separate branches.
